name: Fetch PIB PDFs

on:
  repository_dispatch:
    types: [fetch_pdfs]

jobs:
  fetch-pdfs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Process PIB URLs
        env:
          PDF_URLS: ${{ join(github.event.client_payload.links, ',') }}
          N8N_WEBHOOK: ${{ secrets.N8N_WEBHOOK }}
        run: |
          python fetch_pdfs.py
          
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pib-pdfs
          path: |
            pib_*.pdf
          retention-days: 3
          if-no-files-found: warn
          
      - name: Create summary report
        if: always()
        run: |
          echo "PDF Processing Summary" > summary.md
          echo "=====================" >> summary.md
          echo "Run Date: $(date)" >> summary.md
          echo "Processed URLs: ${{ github.event.client_payload.links.length }}" >> summary.md
          echo "PDFs Downloaded: $(ls pib_*.pdf 2>/dev/null | wc -l)" >> summary.md
          
      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: processing-summary
          path: summary.md
