- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install playwright beautifulsoup4
    playwright install chromium
    playwright install-deps

- name: Convert to PDF
  run: |
    python fetch_pdfs.py
