name: Fetch PIB PDFs

on:
  repository_dispatch:
    types: [fetch-pdfs]  # Must match your event_type

jobs:
  fetch-pdfs:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pdfkit
          
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps
          
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          
      - name: Process PIB URLs
        env:
          PDF_URLS: ${{ join(github.event.client_payload.pdf_urls, ',') }}
          N8N_WEBHOOK: ${{ github.event.client_payload.n8n_webhook || 'https://n8n.maneshwar.com/webhook-test/receive-pdfs' }}
        run: |
          python fetch_pdfs.py
          
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pib-pdfs
          path: |
            pib_*.pdf
          retention-days: 3
          if-no-files-found: warn
