name: Fetch PDFs
on:
  repository_dispatch:
    types: [fetch_pdfs]

jobs:
  fetch-pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Process PIB URLs and fetch PDFs
        env:
          PDF_URLS: ${{ join(github.event.client_payload.links, ',') }}
          N8N_WEBHOOK: ${{ secrets.N8N_WEBHOOK }}  # Set this in repo secrets
        run: |
          python fetch_pdfs.py
          
      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pib-pdfs
          path: "*.pdf"
          if-no-files-found: error
