name: MoSPI Watcher
on:
  schedule:
    - cron: '0 * * * *'  # runs hourly
  workflow_dispatch:      # allows manual trigger

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests beautifulsoup4
      - run: python watcher.py
